# Generated by Django 3.2.5 on 2021-11-28 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.TextField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '19012345678'. Up to 11 digits allowed.",
                        regex="^([1-9][0-9])?[1-9][0-9]{8}",
                    )
                ],
                verbose_name="phone",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="zip_code",
            field=models.TextField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Zip code must be entered in format: '12-345' Up to 5 digits allowed.",
                        regex="^[0-9]{2}-[0-9]{3}",
                    )
                ],
                verbose_name="zip code",
            ),
        ),
    ]
