# Generated by Django 3.2.5 on 2021-12-08 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211128_1526'),
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('ready for consideration', 'Ready For Consideration')], default='ready for consideration', max_length=30, verbose_name='adoption status'),
        ),
        migrations.AddField(
            model_name='cage',
            name='cage_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoption',
            name='ID_series_and_number',
            field=models.TextField(max_length=9, unique=True, verbose_name='ID card series and number'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='adoption_date',
            field=models.DateField(verbose_name='adoption date'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='shelter.cage', verbose_name='cage'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_arrival',
            field=models.DateField(auto_now_add=True, verbose_name='date of arrival'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.TextField(max_length=45, validators=[django.core.validators.RegexValidator(message='Name must start with upper letter and can not have numbers', regex='^[A-Z][a-z]+$')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('addopted', 'Addopted'), ('unavailable', 'Unavailable'), ('available', 'Available')], default='available', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='meetinginfo',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='meetinginfo',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetinginfo_worker', to='authentication.worker'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(verbose_name='reservation date'),
        ),
    ]
