from datetime import datetime
sentence='{} {}'.format('one', 'two')
print(sentence)
sentence2='{} {}'.format(1, 2)
print(sentence2)
sentence3='{:>10}'.format('test')
print(sentence3)
sentence4='{:d}'.format(42)
print(sentence4)
sentence5='{:%Y-%m-%d %H:%M}'.format(datetime(2001, 2, 3, 4, 5))
print(sentence5)